package repository

import "github.com/VMironiuk/offlinescore"

func makeSquad() offlinescore.Squad {
	return offlinescore.Squad{
		Id:          "252",
		Name:        "West Ham United",
		Image:       "enet/8654.png",
		CountryName: "England",
		Players: []offlinescore.Player{
			{
				Id:             "78626",
				FirstName:      "David",
				LastName:       "Moyes",
				ShortName:      "David Moyes",
				CountryName:    "Scotland",
				ActualPosition: 10,
				Position:       10,
			},
			{
				Id:             "30973",
				FirstName:      "Lukasz",
				LastName:       "Fabianski",
				ShortName:      "Lukasz Fabianski",
				CountryName:    "Poland",
				ShirtNumber:    1,
				ActualPosition: 1,
				Position:       1,
				ReasonType:     4,
				ReasonInfo:     "Coronavirus",
				ReturnInfo:     "Day to Day",
				ReturnDate:     20220510,
				ShirtName:      "Lukasz Fabianski",
			},
			{
				Id:             "210164",
				FirstName:      "Alphonse",
				LastName:       "Areola",
				ShortName:      "Alphonse Areola",
				CountryName:    "France",
				ShirtNumber:    13,
				ActualPosition: 1,
				Position:       1,
				ShirtName:      "Alphonse Areola",
			},
			{
				Id:             "155782",
				FirstName:      "Aaron",
				LastName:       "Cresswell",
				ShortName:      "Aaron Cresswell",
				CountryName:    "England",
				ShirtNumber:    3,
				ActualPosition: 2,
				Position:       2,
				ShirtName:      "Aaron Cresswell",
			},
			{
				Id:             "281207",
				FirstName:      "Kurt",
				LastName:       "Zouma",
				ShortName:      "Kurt Zouma",
				CountryName:    "France",
				ShirtNumber:    4,
				ActualPosition: 2,
				Position:       2,
				ShirtName:      "Kurt Zouma",
			},
			{
				Id:             "307317",
				FirstName:      "Vladimir",
				LastName:       "Coufal",
				ShortName:      "Vladimir Coufal",
				CountryName:    "Czech Republic",
				ShirtNumber:    5,
				ActualPosition: 2,
				Position:       2,
				ShirtName:      "Vladimir Coufal",
			},
			{
				Id:             "169162",
				FirstName:      "Craig",
				LastName:       "Dawson",
				ShortName:      "Craig Dawson",
				CountryName:    "England",
				ShirtNumber:    15,
				ActualPosition: 2,
				Position:       2,
				ShirtName:      "Craig Dawson",
			},
			{
				Id:             "696443",
				FirstName:      "Issa",
				LastName:       "Diop",
				ShortName:      "Issa Diop",
				CountryName:    "France",
				ShirtNumber:    23,
				ActualPosition: 2,
				Position:       2,
				ReasonType:     4,
				ReasonInfo:     "Knee Injury",
				ReturnInfo:     "Late February",
				ReturnDate:     20220220,
				ShirtName:      "Issa Diop",
			},
			{
				Id:             "194323",
				FirstName:      "Ryan",
				LastName:       "Fredericks",
				ShortName:      "Ryan Fredericks",
				CountryName:    "England",
				ShirtNumber:    24,
				ActualPosition: 2,
				Position:       2,
				ReasonType:     3,
				ReasonInfo:     "Suspended",
				ReturnInfo:     "3 League Matches",
				ReturnDate:     20220620,
				ShirtName:      "Ryan Fredericks",
			},
			{
				Id:             "418137",
				FirstName:      "Arthur",
				LastName:       "Masuaku",
				ShortName:      "Arthur Masuaku",
				CountryName:    "England",
				ShirtNumber:    26,
				ActualPosition: 2,
				Position:       2,
				ShirtName:      "Arthur Masuaku",
			},
			{
				Id:             "770267",
				FirstName:      "Ben",
				LastName:       "Johnson",
				ShortName:      "Ben Johnson",
				CountryName:    "England",
				ShirtNumber:    31,
				ActualPosition: 2,
				Position:       2,
				ShirtName:      "Ben Johnson",
			},
			{
				Id:             "683450",
				FirstName:      "Pablo",
				LastName:       "Fornals",
				ShortName:      "Pablo Fornals",
				CountryName:    "Spain",
				ShirtNumber:    8,
				ActualPosition: 3,
				Position:       3,
				ShirtName:      "Pablo Fornals",
			},
			{
				Id:             "210276",
				FirstName:      "Manuel",
				LastName:       "Lanzini",
				ShortName:      "Manuel Lanzini",
				CountryName:    "Argentina",
				ShirtNumber:    10,
				ActualPosition: 3,
				Position:       3,
				ShirtName:      "Manuel Lanzini",
			},
			{
				Id:             "524437",
				FirstName:      "Tomas",
				LastName:       "Soucek",
				ShortName:      "Tomas Soucek",
				CountryName:    "Czech Republic",
				ShirtNumber:    28,
				ActualPosition: 3,
				Position:       3,
				ShirtName:      "Tomas Soucek",
			},
			{
				Id:             "836797",
				FirstName:      "Alex",
				LastName:       "Kral",
				ShortName:      "Alex Kral",
				CountryName:    "Czech Republic",
				ShirtNumber:    33,
				ActualPosition: 3,
				Position:       3,
				ShirtName:      "Alex Kral",
			},
			{
				Id:             "654096",
				FirstName:      "Declan",
				LastName:       "Rice",
				ShortName:      "Declan Rice",
				CountryName:    "England",
				ShirtNumber:    41,
				ActualPosition: 3,
				Position:       3,
				ShirtName:      "Declan Rice",
			},
			{
				Id:             "132035",
				FirstName:      "Andriy",
				LastName:       "Yarmolenko",
				ShortName:      "Andriy Yarmolenko",
				CountryName:    "Ukraine",
				ShirtNumber:    7,
				ActualPosition: 4,
				Position:       4,
				ShirtName:      "Andriy Yarmolenko",
			},
			{
				Id:             "158545",
				FirstName:      "Michail",
				LastName:       "Antonio",
				ShortName:      "Michail Antonio",
				CountryName:    "Argentina",
				ShirtNumber:    9,
				ActualPosition: 4,
				Position:       4,
				ShirtName:      "Michail Antonio",
			},
			{
				Id:             "557677",
				FirstName:      "Nikola",
				LastName:       "Vlasic",
				ShortName:      "Nikola Vlasic",
				CountryName:    "England",
				ShirtNumber:    16,
				ActualPosition: 4,
				Position:       4,
				ShirtName:      "Nikola Vlasic",
			},
			{
				Id:             "523825",
				FirstName:      "Jarrod",
				LastName:       "Bowen",
				ShortName:      "Jarrod Bowen",
				CountryName:    "Czech Republic",
				ShirtNumber:    20,
				ActualPosition: 4,
				Position:       4,
				ShirtName:      "Jarrod Bowen",
			},
			{
				Id:             "491883",
				FirstName:      "Said",
				LastName:       "Benrahma",
				ShortName:      "Said Benrahma",
				CountryName:    "Czech Republic",
				ShirtNumber:    22,
				ActualPosition: 4,
				Position:       4,
				ShirtName:      "Said Benrahma",
			},
			{
				Id:             "352672",
				LastName:       "Angelino",
				ShortName:      "Angelino",
				Position:       3,
				PositionString: "MIDFIELDER",
				ShirtNumber:    3,
				ShirtName:      "Angelino",
				ActualPosition: 3,
			},
		},
	}
}
