package repository

import "github.com/VMironiuk/offlinescore"

func makeSquad() offlinescore.Squad {
	return offlinescore.Squad{
		Id:          "252",
		Name:        "West Ham United",
		Image:       "enet/8654.png",
		CountryName: "England",
		Players: []offlinescore.Player{
			{
				Id:                  "78626",
				FirstName:           "David",
				LastName:            "Moyes",
				ShortName:           "David Moyes",
				CountryName:         "Scotland",
				Residence:           "rcd",
				AlternativePosition: 10,
				Position:            10,
			},
			{
				Id:                  "30973",
				FirstName:           "Lukasz",
				LastName:            "Fabianski",
				ShortName:           "Lukasz Fabianski",
				CountryName:         "Poland",
				Residence:           "Poland",
				ShirtNumber:         1,
				AlternativePosition: 1,
				Position:            1,
				ReasonType:          4,
				ReasonInfo:          "Coronavirus",
				ReturnInfo:          "Day to Day",
			},
			{
				Id:                  "210164",
				FirstName:           "Alphonse",
				LastName:            "Areola",
				ShortName:           "Alphonse Areola",
				CountryName:         "France",
				Residence:           "France",
				ShirtNumber:         13,
				AlternativePosition: 1,
				Position:            1,
			},
			{
				Id:                  "155782",
				FirstName:           "Aaron",
				LastName:            "Cresswell",
				ShortName:           "Aaron Cresswell",
				CountryName:         "England",
				Residence:           "England",
				ShirtNumber:         3,
				AlternativePosition: 2,
				Position:            2,
			},
			{
				Id:                  "281207",
				FirstName:           "Kurt",
				LastName:            "Zouma",
				ShortName:           "Kurt Zouma",
				CountryName:         "France",
				Residence:           "France",
				ShirtNumber:         4,
				AlternativePosition: 2,
				Position:            2,
			},
			{
				Id:                  "307317",
				FirstName:           "Vladimir",
				LastName:            "Coufal",
				ShortName:           "Vladimir Coufal",
				CountryName:         "Czech Republic",
				Residence:           "Czech Republic",
				ShirtNumber:         5,
				AlternativePosition: 2,
				Position:            2,
			},
			{
				Id:                  "169162",
				FirstName:           "Craig",
				LastName:            "Dawson",
				ShortName:           "Craig Dawson",
				CountryName:         "England",
				Residence:           "England",
				ShirtNumber:         15,
				AlternativePosition: 2,
				Position:            2,
			},
			{
				Id:                  "696443",
				FirstName:           "Issa",
				LastName:            "Diop",
				ShortName:           "Issa Diop",
				CountryName:         "France",
				Residence:           "France",
				ShirtNumber:         23,
				AlternativePosition: 2,
				Position:            2,
				ReasonType:          4,
				ReasonInfo:          "Knee Injury",
				ReturnInfo:          "Late February",
			},
			{
				Id:                  "194323",
				FirstName:           "Ryan",
				LastName:            "Fredericks",
				ShortName:           "Ryan Fredericks",
				CountryName:         "England",
				Residence:           "England",
				ShirtNumber:         24,
				AlternativePosition: 2,
				Position:            2,
				ReasonType:          3,
				ReasonInfo:          "Suspended",
				ReturnInfo:          "3 League Matches",
			},
			{
				Id:                  "418137",
				FirstName:           "Arthur",
				LastName:            "Masuaku",
				ShortName:           "Arthur Masuaku",
				CountryName:         "England",
				Residence:           "England",
				ShirtNumber:         26,
				AlternativePosition: 2,
				Position:            2,
			},
			{
				Id:                  "770267",
				FirstName:           "Ben",
				LastName:            "Johnson",
				ShortName:           "Ben Johnson",
				CountryName:         "England",
				Residence:           "England",
				ShirtNumber:         31,
				AlternativePosition: 2,
				Position:            2,
			},
			{
				Id:                  "683450",
				FirstName:           "Pablo",
				LastName:            "Fornals",
				ShortName:           "Pablo Fornals",
				CountryName:         "Spain",
				Residence:           "Spain",
				ShirtNumber:         8,
				AlternativePosition: 3,
				Position:            3,
			},
			{
				Id:                  "210276",
				FirstName:           "Manuel",
				LastName:            "Lanzini",
				ShortName:           "Manuel Lanzini",
				CountryName:         "Argentina",
				Residence:           "Argentina",
				ShirtNumber:         10,
				AlternativePosition: 3,
				Position:            3,
			},
			{
				Id:                  "524437",
				FirstName:           "Tomas",
				LastName:            "Soucek",
				ShortName:           "Tomas Soucek",
				CountryName:         "Czech Republic",
				Residence:           "Czech Republic",
				ShirtNumber:         28,
				AlternativePosition: 3,
				Position:            3,
			},
			{
				Id:                  "836797",
				FirstName:           "Alex",
				LastName:            "Kral",
				ShortName:           "Alex Kral",
				CountryName:         "Czech Republic",
				Residence:           "Czech Republic",
				ShirtNumber:         33,
				AlternativePosition: 3,
				Position:            3,
			},
			{
				Id:                  "654096",
				FirstName:           "Declan",
				LastName:            "Rice",
				ShortName:           "Declan Rice",
				CountryName:         "England",
				Residence:           "England",
				ShirtNumber:         41,
				AlternativePosition: 3,
				Position:            3,
			},
			{
				Id:                  "132035",
				FirstName:           "Andriy",
				LastName:            "Yarmolenko",
				ShortName:           "Andriy Yarmolenko",
				CountryName:         "Ukraine",
				Residence:           "Ukraine",
				ShirtNumber:         7,
				AlternativePosition: 4,
				Position:            4,
			},
			{
				Id:                  "158545",
				FirstName:           "Michail",
				LastName:            "Antonio",
				ShortName:           "Michail Antonio",
				CountryName:         "Argentina",
				Residence:           "Argentina",
				ShirtNumber:         9,
				AlternativePosition: 4,
				Position:            4,
			},
			{
				Id:                  "557677",
				FirstName:           "Nikola",
				LastName:            "Vlasic",
				ShortName:           "Nikola Vlasic",
				CountryName:         "England",
				Residence:           "England",
				ShirtNumber:         16,
				AlternativePosition: 4,
				Position:            4,
			},
			{
				Id:                  "523825",
				FirstName:           "Jarrod",
				LastName:            "Bowen",
				ShortName:           "Jarrod Bowen",
				CountryName:         "Czech Republic",
				Residence:           "Czech Republic",
				ShirtNumber:         20,
				AlternativePosition: 4,
				Position:            4,
			},
			{
				Id:                  "491883",
				FirstName:           "Said",
				LastName:            "Benrahma",
				ShortName:           "Said Benrahma",
				CountryName:         "Czech Republic",
				Residence:           "Czech Republic",
				ShirtNumber:         22,
				AlternativePosition: 4,
				Position:            4,
			},
		},
	}
}
